[tox]
minversion = 4.28.0
envlist = py3,pep8

[testenv]
constrain_package_deps = true
setenv = VIRTUAL_ENV={envdir}
         PYTHONDONTWRITEBYTECODE = 1
         LANGUAGE=en_US
         # .stestr.conf uses TESTS_DIR
         TESTS_DIR=./ironicclient/tests/unit
usedevelop = True
constraints =
    {env:TOX_CONSTRAINTS_FILE:https://releases.openstack.org/constraints/upper/master}
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/test-requirements.txt
commands =
    stestr run {posargs}

[testenv:releasenotes]
deps =
    -r{toxinidir}/doc/requirements.txt
commands = sphinx-build -a -E -W -d releasenotes/build/doctrees -b html releasenotes/source releasenotes/build/html

[testenv:pep8]
allowlist_externals = pre-commit
deps = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure {posargs}

[testenv:mypy]
description =
    Run type checks.
deps =
    {[testenv]deps}
commands =
    mypy --cache-dir="{envdir}/mypy_cache" {posargs}

[testenv:cover]
setenv = {[testenv]setenv}
         PYTHON=coverage run --source ironicclient --omit='*tests*' --parallel-mode
commands =
    coverage erase
    stestr run {posargs}
    coverage combine
    coverage report --omit='*tests*'
    coverage html -d ./cover --omit='*tests*'

[testenv:venv]
deps =
    -r{toxinidir}/test-requirements.txt
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/doc/requirements.txt
commands = {posargs}

[testenv:docs]
deps =
    -r{toxinidir}/doc/requirements.txt
commands =
    sphinx-build -W -b html doc/source doc/build/html

[testenv:pdf-docs]
allowlist_externals = make
deps = {[testenv:docs]deps}
commands =
    sphinx-build -W -b latex doc/source doc/build/pdf
    make -C doc/build/pdf

[flake8]
ignore = W503
exclude = .venv,.git,.tox,dist,doc,*lib/python*,*egg,build,tools
# [H106] Don't put vim configuration in source files.
# [H203] Use assertIs(Not)None to check for None.
# [H204] Use assert(Not)Equal to check for equality.
# [H205] Use assert(Greater|Less)(Equal) for comparison.
# [H210] Require 'autospec', 'spec', or 'spec_set' in mock.patch/mock.patch.object calls
# [H904] Delay string interpolations at logging calls.
enable-extensions=H106,H203,H204,H205,H210,H904
filename = *.py
import-order-style = pep8
application-import-names = ironicclient

[hacking]
import_exceptions =
  collections.abc
  ironicclient.common.i18n
  typing

[testenv:codespell]
description =
  Run codespell to check spelling
deps = {[testenv:pep8]deps}
commands = pre-commit run --all-files --show-diff-on-failure codespell
