- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-master-branch-jobs
      - openstack-python3-yoga-jobs
      - openstackclient-plugin-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
# NOTE(JayF): Disabled 2023-08-23, jobs are not passing and required
#             fix to zuul config must merge.
#    check:
#      jobs:
#        - ironicclient-functional
#        - ironicclient-tempest
#    gate:
#      jobs:
#        - ironicclient-functional
#        - ironicclient-tempest
