- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-jobs
      - openstackclient-plugin-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - ironicclient-tempest
        - ironicclient-tox-codespell:
            voting: false
