- project:
    name: openstack/python-ironicclient
    check:
      jobs:
        - ironicclient-dsvm-functional
        - ironicclient-tempest-dsvm-src
    gate:
      queue: ironic
      jobs:
        - ironicclient-dsvm-functional
        - ironicclient-tempest-dsvm-src
