- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-antelope-jobs
      - openstackclient-plugin-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        # NOTE(rpittau): temp non-voting until we fix it
        - ironicclient-functional:
            voting: false
        - ironicclient-tempest
        - ironicclient-tox-codespell:
            voting: false
    gate:
      jobs:
        # NOTE(rpittau): temp non-voting until we fix it
        #- ironicclient-functional
        - ironicclient-tempest
